import type { Metadata } from "next";
import "./globals.css";

import { ReactLenis } from "lenis/react";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "HM SERVICES AND LOGISTICS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full bg-white">
        <ReactLenis
          root
          options={{
            lerp: 0.05,
            duration: 1.5,
          }}
        >
          <Navbar />
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}